siteName: Ear protectors
title: Ear protectors
author: David White
url: https://github.com/webdigga/ear-protectors
poweredBy: Seven Kings
description: Some description here for search engines
type: Product
logoUrl: 
logoAlt: Some logo alt text here