siteName: Moulded Ear Plugs
title: Moulded Ear Plugs
author: David White
url: https://github.com/webdigga/ear-protectors
poweredBy: Arragon Affiliates
description: A wide range of moulded and custom made earplugs designed for
  various activities including shooting, biking, swimming, sleeping, travel,
  music, concerts, and work. Protect your hearing with precision-fit solutions
  tailored to your lifestyle.
type: website
logoAlt: Moulded Ear Plugs logo
logoUrl: /static/img/website_logo.webp
