siteName: Moulded earplugs
title: Moulded earplugs
author: David White
url: https://github.com/webdigga/ear-protectors
poweredBy: Arragon Affiliates
description: A range of Moulded earplug reviews
type: Product
logoAlt: Moulded earplugs logo
logoUrl: /static/img/website_logo.jpg
