siteName: Best Ear Plugs
title: Best Ear Plugs
author: David White
url: https://github.com/webdigga/best-ear-plugs
poweredBy: Arragon Affiliates
description: Discover the best ear plugs for sleep, noise reduction, and comfort. Explore top-rated options and expert reviews to find the perfect fit for your needs
type: website
logoAlt: Best Ear Plugs logo
logoUrl: /static/img/bep-logo.png
