siteName: Ear protectors
title: Ear protectors
author: https://ear-protectors.netlify.app/admin/#/collections/settingsDavid White
url: https://github.com/webdigga/ear-protectors
poweredBy: Arragon Affiliates
description: Some description here for search engines
type: Product
logoAlt: Some logo alt text here
logoUrl: /static/img/website_logo.jpg
