siteName: Best Ear Plugs
title: Best Ear Plugs
author: David White
url: https://github.com/webdigga/best-ear-plugs
poweredBy: Arragon Affiliates
description: A selection of the best ear plugs for sport, sleeping, travel and music.
type: website
logoAlt: Best Ear Plugs logo
logoUrl: /static/img/bep-logo.png
